# -*- coding: utf-8 -*-
"""Copy of LVADSUSR102-PrabuT-IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c9dqVSRyAdZ9oFtyjaLm8rTOKy8OXTpg
"""

#1
import numpy as np
rgb_image=np.array([[[255,0,0],[0,255,0],[0,0,255]],
                    [[255,255,0],[255,0,255],[0,255,255]],
                    [[127,127,127],[200,200,200],[50,50,50]]])
print(rgb_image)
print(0.2989rgb_image[0]+0.5870rgb_image[1]+0.1140*rgb_image[2])

#2

#3
import numpy as np
thr_arr=[[[2,3,5],[1,2,4]],[[2,3,5],[1,2,3]],[[3,4,6],[2,3,5]]]
np_ar=np.array(thr_arr)
flat=np_ar.flatten()
print(flat.reshape(1,6))

#4

#5

#6

#7
data={
    'Names':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
    'Age':[25,30,35,40,45,50,55],
    'City':['New York','Los Angeles','Chicago','Houstan','Phoenix','Miami','Boston'],
    'Department':['HR','IT','Finance','Marketing','Sales','IT','HR']
}
df=pd.DataFrame(data)
new_df=df[df['Age']<45]
new_df=new_df[new_df['Department']!='HR']
print(new_df)

#8
import pandas as pd
market_data={
    'Product':['Apples','Bananas','Cherries','Dates','Elderberries','Floor','Grape'],
    'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery','Fruit'],
    'Price':[1.20,0.50,3.00,2.50,4.00,1.50,2.00],
    'Promotion':[True,False,True,True,False,True,False]
}
df_market_data=pd.DataFrame(market_data)
avg_value=df_market_data.groupby('Category')['Price'].mean()
df_new=df_market_data['Price'>avg_value['Fruit']] and df_market_data['Promotion'==False]
print(df_new)

#9
import pandas as pd

employee_data={'Employee':['Alice','Bob','Charlie','David'],
               'Department':['HR','IT','Finance','IT'],
               'Manager':['John','Rachel','Emily','Rachel']}
project_data={
    'Employee':['Alice','Charlie','Eve'],
    'Project':['P1','P2','P3']
}
df1=pd.DataFrame(employee_data,columns=['Employee','Department','Manager'])
df2=pd.DataFrame(project_data,columns=['Employee','Project'])
merged_data=pd.merge(df1,df2,on='Employee',how='outer')
print(merged_data)

#Q10
data = {
    'Department' : ['Electronics', 'Electronics','Clothing','Clothing','Home Goods'],
    'Salesperson' : ['Alice','Bob','Charlie','David','Eve'],
    'Sales': [70000,50000,30000,40000,60000]
}
df = pd.DataFrame(data)
avg_salesperson = df.groupby('Department')['Sales'].mean()
rank_dept = avg_sales_per_salesperson.sort_values(ascending=False)


print(avg_salesperson)
print("-----Based on rank-----")
print(rank_dept)